export interface LanguageOption {
  value: string;
  label: string;
}

export const LANGUAGE_OPTIONS: LanguageOption[] = [
  { value: "Afrikaans", label: "Afrikaans (af)" },
  { value: "Albanian", label: "Albanian (sq)" },
  { value: "Amharic", label: "Amharic (am)" },
  { value: "Arabic", label: "Arabic (ar)" },
  { value: "Armenian", label: "Armenian (hy)" },
  { value: "Azerbaijani", label: "Azerbaijani (az)" },
  { value: "Basque", label: "Basque (eu)" },
  { value: "Belarusian", label: "Belarusian (be)" },
  { value: "Bengali", label: "Bengali (bn)" },
  { value: "Bosnian", label: "Bosnian (bs)" },
  { value: "Bulgarian", label: "Bulgarian (bg)" },
  { value: "Catalan", label: "Catalan (ca)" },
  { value: "Chinese (Mandarin)", label: "Chinese, Mandarin (zh)" },
  { value: "Chinese (Cantonese)", label: "Chinese, Cantonese (yue)" },
  { value: "Croatian", label: "Croatian (hr)" },
  { value: "Czech", label: "Czech (cs)" },
  { value: "Danish", label: "Danish (da)" },
  { value: "Dutch", label: "Dutch (nl)" },
  { value: "English", label: "English (en)" },
  { value: "Estonian", label: "Estonian (et)" },
  { value: "Finnish", label: "Finnish (fi)" },
  { value: "French", label: "French (fr)" },
  { value: "Galician", label: "Galician (gl)" },
  { value: "Georgian", label: "Georgian (ka)" },
  { value: "German", label: "German (de)" },
  { value: "Greek", label: "Greek (el)" },
  { value: "Gujarati", label: "Gujarati (gu)" },
  { value: "Haitian Creole", label: "Haitian Creole (ht)" },
  { value: "Hausa", label: "Hausa (ha)" },
  { value: "Hebrew", label: "Hebrew (he)" },
  { value: "Hindi", label: "Hindi (hi)" },
  { value: "Hungarian", label: "Hungarian (hu)" },
  { value: "Icelandic", label: "Icelandic (is)" },
  { value: "Igbo", label: "Igbo (ig)" },
  { value: "Indonesian", label: "Indonesian (id)" },
  { value: "Irish", label: "Irish (ga)" },
  { value: "Italian", label: "Italian (it)" },
  { value: "Japanese", label: "Japanese (ja)" },
  { value: "Javanese", label: "Javanese (jv)" },
  { value: "Kannada", label: "Kannada (kn)" },
  { value: "Kazakh", label: "Kazakh (kk)" },
  { value: "Khmer", label: "Khmer (km)" },
  { value: "Korean", label: "Korean (ko)" },
  { value: "Kurdish", label: "Kurdish (ku)" },
  { value: "Kyrgyz", label: "Kyrgyz (ky)" },
  { value: "Lao", label: "Lao (lo)" },
  { value: "Latin", label: "Latin (la)" },
  { value: "Latvian", label: "Latvian (lv)" },
  { value: "Lithuanian", label: "Lithuanian (lt)" },
  { value: "Macedonian", label: "Macedonian (mk)" },
  { value: "Malay", label: "Malay (ms)" },
  { value: "Malayalam", label: "Malayalam (ml)" },
  { value: "Maltese", label: "Maltese (mt)" },
  { value: "Marathi", label: "Marathi (mr)" },
  { value: "Mongolian", label: "Mongolian (mn)" },
  { value: "Nepali", label: "Nepali (ne)" },
  { value: "Norwegian", label: "Norwegian (no)" },
  { value: "Pashto", label: "Pashto (ps)" },
  { value: "Persian", label: "Persian (fa)" },
  { value: "Polish", label: "Polish (pl)" },
  { value: "Portuguese", label: "Portuguese (pt)" },
  { value: "Punjabi", label: "Punjabi (pa)" },
  { value: "Romanian", label: "Romanian (ro)" },
  { value: "Russian", label: "Russian (ru)" },
  { value: "Serbian", label: "Serbian (sr)" },
  { value: "Sinhalese", label: "Sinhalese (si)" },
  { value: "Slovak", label: "Slovak (sk)" },
  { value: "Slovenian", label: "Slovenian (sl)" },
  { value: "Somali", label: "Somali (so)" },
  { value: "Spanish", label: "Spanish (es)" },
  { value: "Swahili", label: "Swahili (sw)" },
  { value: "Swedish", label: "Swedish (sv)" },
  { value: "Tagalog", label: "Tagalog (tl)" },
  { value: "Tajik", label: "Tajik (tg)" },
  { value: "Tamil", label: "Tamil (ta)" },
  { value: "Telugu", label: "Telugu (te)" },
  { value: "Thai", label: "Thai (th)" },
  { value: "Turkish", label: "Turkish (tr)" },
  { value: "Turkmen", label: "Turkmen (tk)" },
  { value: "Ukrainian", label: "Ukrainian (uk)" },
  { value: "Urdu", label: "Urdu (ur)" },
  { value: "Uzbek", label: "Uzbek (uz)" },
  { value: "Vietnamese", label: "Vietnamese (vi)" },
  { value: "Welsh", label: "Welsh (cy)" },
  { value: "Xhosa", label: "Xhosa (xh)" },
  { value: "Yoruba", label: "Yoruba (yo)" },
  { value: "Zulu", label: "Zulu (zu)" },
  { value: "Instrumental", label: "Instrumental (zxx)" },
];
