// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ingestion-form/FreshWave.tsx": () => import("../components/mockups/ingestion-form/FreshWave.tsx"),
  "./components/mockups/ingestion-form/NightOps.tsx": () => import("../components/mockups/ingestion-form/NightOps.tsx"),
  "./components/mockups/ingestion-form/WarmStudio.tsx": () => import("../components/mockups/ingestion-form/WarmStudio.tsx")
};
